INSERT INTO tbl_country (country_value,country_name,region,is_active) VALUES 
('AF', 'Afghanistan', 'Asia', 0),
('DZ', 'Algeria', 'Africa', 0),
('AS', 'American Samoa', 'Oceania', 0),
('AD', 'Andorra', 'Europe', 0),
('AO', 'Angola', 'Africa', 0),
('AI', 'Anguilla', 'Central America and Caribbean', 0),
('AG', 'Antigua and Barbuda', 'Central America and Caribbean', 0),
('AR', 'Argentina', 'South America', 0),
('AM', 'Armenia', 'Asia', 0),
('AW', 'Aruba', 'Central America and Caribbean', 0),
('AU', 'Australia', 'Oceania', 0),
('AT', 'Austria', 'Europe', 0),
('AZ', 'Azerbaijan Republic', 'Asia', 0),
('BS', 'Bahamas', 'Central America and Caribbean', 0),
('BD', 'Bangladesh', 'Asia', 0),
('BB', 'Barbados', 'Central America and Caribbean', 0),
('BY', 'Belarus', 'Europe', 0),
('BE', 'Belgium', 'Europe', 0),
('BZ', 'Belize', 'Central America and Caribbean', 0),
('BJ', 'Benin', 'Africa', 0),
('BM', 'Bermuda', 'North America', 0),
('BT', 'Bhutan', 'Asia', 0),
('BO', 'Bolivia', 'South America', 0),
('BA', 'Bosnia and Herzegovina', 'Europe', 0),
('BW', 'Botswana', 'Africa', 0),
('BR', 'Brazil', 'South America', 0),
('BG', 'Bulgaria', 'Europe', 0),
('BF', 'Burkina Faso', 'Africa', 0),
('BI', 'Burundi', 'Africa', 0),
('KH', 'Cambodia', 'Asia', 0),
('CM', 'Cameroon', 'Africa', 0),
('CA', 'Canada', 'North America', 0),
('CV', 'Cape Verde Islands', 'Africa', 0),
('KY', 'Cayman Islands', 'Central America and Caribbean', 0),
('CF', 'Central African Republic', 'Africa', 0),
('TD', 'Chad', 'Africa', 0),
('CL', 'Chile', 'South America', 0),
('CO', 'Colombia', 'South America', 0),
('KM', 'Comoros', 'Africa', 0),
('ZR', 'Congo, Democratic Republic of the', 'Africa', 0),
('CG', 'Congo, Republic of the', 'Africa', 0),
('CK', 'Cook Islands', 'Oceania', 0),
('CR', 'Costa Rica', 'Central America and Caribbean', 0),
('CI', 'Ivory Coast', 'Africa', 0),
('HR', 'Croatia, Republic of', 'Europe', 0),
('CY', 'Cyprus', 'Europe', 0),
('CZ', 'Czech Republic', 'Europe', 0),
('DK', 'Denmark', 'Europe', 0),
('DJ', 'Djibouti', 'Africa', 0),
('DM', 'Dominica', 'Central America and Caribbean', 0),
('DO', 'Dominican Republic', 'Central America and Caribbean', 0),
('EC', 'Ecuador', 'South America', 0),
('EG', 'Egypt', 'Africa', 0),
('SV', 'El Salvador', 'Central America and Caribbean', 0),
('GQ', 'Equatorial Guinea', 'Africa', 0),
('ER', 'Eritrea', 'Africa', 0),
('EE', 'Estonia', 'Europe', 0),
('ET', 'Ethiopia', 'Africa', 0),
('FK', 'Falkland Islands (Islas Malvinas)', 'South America', 0),
('FJ', 'Fiji', 'Oceania', 0),
('FI', 'Finland', 'Europe', 0),
('FR', 'France', 'Europe', 0),
('GF', 'French Guiana', 'South America', 0),
('PF', 'French Polynesia', 'Oceania', 0),
('GA', 'Gabon Republic', 'Africa', 0),
('GM', 'Gambia', 'Africa', 0),
('GE', 'Georgia', 'Asia', 0),
('DE', 'Germany', 'Europe', 0),
('GH', 'Ghana', 'Africa', 0),
('GI', 'Gibraltar', 'Europe', 0),
('GR', 'Greece', 'Europe', 0),
('GL', 'Greenland', 'North America', 0),
('GD', 'Grenada', 'Central America and Caribbean', 0),
('GP', 'Guadeloupe', 'Central America and Caribbean', 0),
('GU', 'Guam', 'Oceania', 0),
('GT', 'Guatemala', 'Central America and Caribbean', 0),
('GGY', 'Guernsey', 'Europe', 0),
('GN', 'Guinea', 'Africa', 0),
('GW', 'Guinea-Bissau', 'Africa', 0),
('GY', 'Guyana', 'South America', 0),
('HT', 'Haiti', 'Central America and Caribbean', 0),
('HN', 'Honduras', 'Central America and Caribbean', 0),
('HK', 'Hong Kong', 'Asia', 0),
('HU', 'Hungary', 'Europe', 0),
('IS', 'Iceland', 'Europe', 0),
('IN', 'India', 'Asia', 0),
('ID', 'Indonesia', 'Asia', 0),
('IQ', 'Iraq', 'Asia', 0),
('IE', 'Ireland', 'Europe', 0),
('IL', 'Israel', 'Asia', 0),
('IT', 'Italy', 'Europe', 0),
('JM', 'Jamaica', 'Central America and Caribbean', 0),
('JP', 'Japan', 'Asia', 0),
('JEY', 'Jersey', 'Europe', 0),
('JO', 'Jordan', 'Asia', 0),
('KZ', 'Kazakhstan', 'Asia', 0),
('KE', 'Kenya', 'Africa', 0),
('KI', 'Kiribati', 'Oceania', 0),
('KW', 'Kuwait', 'Asia', 0),
('KG', 'Kyrgyzstan', 'Asia', 0),
('LA', 'Laos', 'Asia', 0),
('LV', 'Latvia', 'Europe', 0),
('LB', 'Lebanon', 'Asia', 0),
('LS', 'Lesotho', 'Africa', 0),
('LR', 'Liberia', 'Africa', 0),
('LY', 'Libya', 'Africa', 0),
('LI', 'Liechtenstein', 'Europe', 0),
('LT', 'Lithuania', 'Europe', 0),
('LU', 'Luxembourg', 'Europe', 0),
('MO', 'Macau', 'Asia', 0),
('MK', 'Macedonia', 'Europe', 0),
('MG', 'Madagascar', 'Africa', 0),
('MW', 'Malawi', 'Africa', 0),
('MY', 'Malaysia', 'Asia', 0),
('MV', 'Maldives', 'Asia', 0),
('ML', 'Mali', 'Africa', 0),
('MT', 'Malta', 'Europe', 0),
('MH', 'Marshall Islands', 'Oceania', 0),
('MQ', 'Martinique', 'Central America and Caribbean', 0),
('MR', 'Mauritania', 'Africa', 0),
('MU', 'Mauritius', 'Africa', 0),
('YT', 'Mayotte', 'Africa', 0),
('MX', 'Mexico', 'North America', 0),
('FM', 'Micronesia', 'Oceania', 0),
('MD', 'Moldova', 'Europe', 0),
('MC', 'Monaco', 'Europe', 0),
('MN', 'Mongolia', 'Asia', 0),
('MNE', 'Montenegro', 'Europe', 0),
('MS', 'Montserrat', 'Central America and Caribbean', 0),
('MA', 'Morocco', 'Africa', 0),
('MZ', 'Mozambique', 'Africa', 0),
('NA', 'Namibia', 'Africa', 0),
('NR', 'Nauru', 'Oceania', 0),
('NP', 'Nepal', 'Asia', 0),
('NL', 'Netherlands', 'Europe', 0),
('AN', 'Netherlands Antilles', 'Central America and Caribbean', 0),
('NC', 'New Caledonia', 'Oceania', 0),
('NZ', 'New Zealand', 'Oceania', 0),
('NI', 'Nicaragua', 'Central America and Caribbean', 0),
('NE', 'Niger', 'Africa', 0),
('NG', 'Nigeria', 'Africa', 0),
('NU', 'Niue', 'Oceania', 0),
('NO', 'Norway', 'Europe', 0),
('OM', 'Oman', 'Asia', 0),
('PK', 'Pakistan', 'Asia', 0),
('PW', 'Palau', 'Oceania', 0),
('PA', 'Panama', 'Central America and Caribbean', 0),
('PG', 'Papua New Guinea', 'Oceania', 0),
('PY', 'Paraguay', 'South America', 0),
('PE', 'Peru', 'South America', 0),
('PH', 'Philippines', 'Asia', 0),
('PL', 'Poland', 'Europe', 0),
('PT', 'Portugal', 'Europe', 0),
('PR', 'Puerto Rico', 'Central America and Caribbean', 0),
('QA', 'Qatar', 'Asia', 0),
('RE', 'Reunion', 'Africa', 0),
('RO', 'Romania', 'Europe', 0),
('RU', 'Russian Federation', 'Asia', 0),
('RW', 'Rwanda', 'Africa', 0),
('KN', 'Saint Kitts-Nevis', 'Central America and Caribbean', 0),
('LC', 'Saint Lucia', 'Central America and Caribbean', 0),
('VC', 'Saint Vincent and the Grenadines', 'Central America and Caribbean', 0),
('SM', 'San Marino', 'Europe', 0),
('SA', 'Saudi Arabia', 'Asia', 0),
('SN', 'Senegal', 'Africa', 0),
('SRB', 'Serbia', 'Europe', 0),
('SC', 'Seychelles', 'Africa', 0),
('SL', 'Sierra Leone', 'Africa', 0),
('SG', 'Singapore', 'Asia', 0),
('SK', 'Slovakia', 'Europe', 0),
('SI', 'Slovenia', 'Europe', 0),
('SB', 'Solomon Islands', 'Oceania', 0),
('SO', 'Somalia', 'Africa', 0),
('ZA', 'South Africa', 'Africa', 0),
('KR', 'South Korea', 'Asia', 0),
('ES', 'Spain', 'Europe', 0),
('LK', 'Sri Lanka', 'Asia', 0),
('SR', 'Suriname', 'South America', 0),
('SZ', 'Swaziland', 'Africa', 0),
('SE', 'Sweden', 'Europe', 0),
('CH', 'Switzerland', 'Europe', 0),
('TW', 'Taiwan', 'Asia', 0),
('TJ', 'Tajikistan', 'Asia', 0),
('TZ', 'Tanzania', 'Africa', 0),
('TH', 'Thailand', 'Asia', 0),
('TG', 'Togo', 'Africa', 0),
('TO', 'Tonga', 'Oceania', 0),
('TT', 'Trinidad and Tobago', 'Central America and Caribbean', 0),
('TN', 'Tunisia', 'Africa', 0),
('TR', 'Turkey', 'Asia', 0),
('TM', 'Turkmenistan', 'Asia', 0),
('TC', 'Turks and Caicos Islands', 'Central America and Caribbean', 0),
('TV', 'Tuvalu', 'Oceania', 0),
('UG', 'Uganda', 'Africa', 0),
('UA', 'Ukraine', 'Europe', 0),
('AE', 'United Arab Emirates', 'Asia', 0),
('GB', 'United Kingdom', 'Europe', 0),
('US', 'United States', 'North America', 0),
('UY', 'Uruguay', 'South America', 0),
('UZ', 'Uzbekistan', 'Asia', 0),
('VU', 'Vanuatu', 'Oceania', 0),
('VA', 'Vatican City State', 'Europe', 0),
('VE', 'Venezuela', 'South America', 0),
('VN', 'Vietnam', 'Asia', 0),
('VI', 'Virgin Islands (U.S.)', 'Central America and Caribbean', 0),
('WF', 'Wallis and Futuna', 'Oceania', 0),
('YE', 'Yemen', 'Asia', 0),
('ZM', 'Zambia', 'Africa', 0),
('ZW', 'Zimbabwe', 'Africa', 0)